spring.application.name=demo1
spring.datasource.url=jdbc:oracle:thin:@10.10.0.202:1521:orcl
spring.datasource.username=DEMO
spring.datasource.password=DEMO
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

jwt.secret=doi-chuoi-nay-thanh-random-string-that-dai-toi-thieu-32-ky-tu-khi-len-prod
jwt.expiration-ms=86400000

#spring.application.name=demo1
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
#spring.datasource.username=system
#spring.datasource.password=NTA
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect