#db cty
#
#spring.application.name=demo1
#spring.datasource.url=jdbc:oracle:thin:@10.10.0.202:1521:orcl
#spring.datasource.username=DEMO
#spring.datasource.password=DEMO
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

#db nta

spring.application.name=demo1
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=system
spring.datasource.password=NTA
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect



jwt.secret=doi-chuoi-nay-thanh-random-string-that-dai-toi-thieu-32-ky-tu-khi-len-prod
jwt.expiration-ms=86400000

# ==================================================
# MINIO
# ==================================================

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin123
minio.bucket=payment-hub-exports


# ==================================================
# EXPORT
# ==================================================

# T?i ?a 2 export ch?y ??ng th?i
export.max-concurrent-workers=2

# Scheduler tìm job NEW m?i 5 giây
export.poll-interval-ms=1000

# Check job PROCESSING b? k?t
export.stale-check-interval-ms=60000

# T?m ?? cao khi export 500k - 1tr
export.stale-after-minutes=120

# SXSSF gi? 200 row trong RAM
export.sxssf-window-size=500

# Oracle JDBC l?y 1000 row m?i fetch
export.jdbc-fetch-size=20000

# Presigned URL t?n t?i 1 ngày
export.presigned-url-expiry-minutes=1440

# File Excel t?m
export.temp-dir=${java.io.tmpdir}

# Dùng cho MinIO lifecycle
export.retention-days=7


# ==================================================
# HIKARI
# ==================================================

spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5